typography_spectrum: 0.60849
content_rating:
  adult: false
color:
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
  brandStrength: 0.875
  lightness: 0.25
  saturation: 0.875
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: ''
  appId: ''
layout_spectrum: 0.32846
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Michal Graf
  url: ''
  email: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/491aa32f-7567-4ca2-8536-c3c07f9528da.jpg
name: collagen.boutique
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Products
    id: 7487681d-3b79-46e4-856c-5e26f71f2a96
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/33e277a2-3744-4f94-b5e5-9d4889589ff3.jpg
title: Exclusive support for you and your body
purpose: []
