name: collagen.boutique
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/33e277a2-3744-4f94-b5e5-9d4889589ff3.jpg
layout_spectrum: 0.4208437120912748
typography_spectrum: 0.60849
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/491aa32f-7567-4ca2-8536-c3c07f9528da.jpg
title: Exclusive support for you and your body
author:
  name: Michal Graf
  url: ''
  email: ''
content_rating:
  adult: false
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: ''
  appId: ''
color:
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
  brandStrength: 0.875
  lightness: 0.25
  saturation: 0.875
  rhythmicContrast: 0.5
purpose: []
